"""Deterministic in-process AgentAdapter used by FastLab tests."""

import json
import os
import re
import threading
import time
import uuid
from pathlib import Path

from agent_adapter import (
    AgentAdapter, PLAN_CAPABILITY, RESUME_CAPABILITY, SKILLS_CAPABILITY,
    VERIFY_CAPABILITY, WRITE_CAPABILITY,
)


class FakeAgentAdapter(AgentAdapter):
    kind = "fake-codex-cli"
    capabilities = frozenset({
        PLAN_CAPABILITY, WRITE_CAPABILITY, RESUME_CAPABILITY,
        VERIFY_CAPABILITY, SKILLS_CAPABILITY,
    })

    def __init__(self):
        self.calls = []
        self.active = set()
        self.max_active = 0
        self.lock = threading.Lock()

    def run(self, key, cwd, prompt, sandbox, schema=None, resume_session=None,
            on_event=None, model=None, effort=None, skills=None,
            local_network=False):
        thread_id = resume_session or "fake-" + uuid.uuid4().hex[:12]
        call = {
            "key": key, "cwd": str(cwd), "sandbox": sandbox, "model": model,
            "effort": effort, "skills": [item["name"] for item in (skills or [])],
            "local_network": bool(local_network),
            "resume": resume_session, "prompt": prompt,
            "started_at": time.monotonic(), "ended_at": None,
        }
        self.calls.append(call)
        with self.lock:
            self.active.add(key)
            self.max_active = max(self.max_active, len(self.active))
        try:
            if on_event:
                on_event("thread.started", "Codex 已连接", {"thread_id": thread_id})
                on_event("turn.started", "开始", {"type": "turn.started"})
            delay = float(os.environ.get("FASTLAB_FAKE_DELAY", "0"))
            deadline = time.time() + delay
            while time.time() < deadline:
                if key not in self.active:
                    return 130, thread_id, ""
                time.sleep(0.02)
            if "planner" in key:
                final = json.dumps(self._plan(prompt), ensure_ascii=False)
            elif "verifier" in key:
                if os.environ.get("FASTLAB_FAKE_VERIFY_ERROR"):
                    return 1, thread_id, "API Error: 402 Insufficient Balance"
                if os.environ.get("FASTLAB_FAKE_VERIFY_UNCLEAR"):
                    final = json.dumps({
                        "passed": False,
                        "summary": "自动检查通过，浏览器交互需要人工确认。",
                        "results": [
                            {"id": "A1", "status": "passed", "evidence": "结果文件存在。"},
                            {"id": "A2", "status": "unclear", "evidence": "请在浏览器点击主按钮并确认结果。"},
                        ],
                    }, ensure_ascii=False)
                else:
                    final = json.dumps({
                        "passed": True,
                        "summary": "测试验收通过。",
                        "results": [
                            {"id": "A1", "status": "passed", "evidence": "结果文件存在。"},
                            {"id": "A2", "status": "passed", "evidence": "主分支提交未变化。"},
                        ],
                    }, ensure_ascii=False)
            else:
                match = re.search(r"子任务 ID：?(S\d+)", prompt)
                task_key = match.group(1) if match else "S1"
                if os.environ.get("FASTLAB_FAKE_FAIL_KEY") == task_key:
                    return 7, thread_id, ""
                if os.environ.get("FASTLAB_FAKE_RAISE_KEY") == task_key:
                    raise RuntimeError("模拟 SDK 传输异常")
                if "本轮新增要求" in prompt:
                    filename = "revision-%s.txt" % task_key
                else:
                    filename = "followup-%s.txt" % task_key if resume_session else "result-%s.txt" % task_key
                if "CONFLICT" in prompt:
                    filename = "shared.txt"
                destination = Path(cwd)
                scope_match = re.search(r"^允许写入范围：(.+)$", prompt, re.MULTILINE)
                if scope_match and scope_match.group(1).strip() != "整个仓库":
                    destination = destination / scope_match.group(1).strip().removesuffix("/**")
                if os.environ.get("FASTLAB_FAKE_OUTSIDE_SCOPE"):
                    destination = Path(cwd)
                destination.mkdir(parents=True, exist_ok=True)
                (destination / filename).write_text(
                    "generated by %s\n" % task_key, encoding="utf-8"
                )
                final = json.dumps({"ok": True, "subtask": task_key})
            if on_event:
                on_event("item.completed", final, {"type": "item.completed"})
                on_event("turn.completed", "完成", {"type": "turn.completed"})
            return 0, thread_id, final
        finally:
            call["ended_at"] = time.monotonic()
            with self.lock:
                self.active.discard(key)

    @staticmethod
    def _plan(prompt=""):
        plan = {
            "title": "测试任务",
            "summary": "用三个子任务验证并行执行、依赖调度和任务分支汇总。",
            "subtasks": [
                {"key": "S1", "title": "创建第一份结果", "instructions": "创建 S1 的结果文件。", "weight": 2, "dependencies": [], "executor": "codex"},
                {"key": "S2", "title": "创建第二份结果", "instructions": "创建 S2 的结果文件。", "weight": 1, "dependencies": [], "executor": "codex"},
                {"key": "S3", "title": "完成依赖任务", "instructions": "在 S1、S2 完成后创建最终结果。", "weight": 1, "dependencies": ["S1", "S2"], "executor": "codex"},
            ],
            "acceptance": [
                {"id": "A1", "criterion": "三个结果文件存在。"},
                {"id": "A2", "criterion": "主分支没有被修改。"},
            ],
        }
        return plan

    def interrupt(self, key):
        with self.lock:
            existed = key in self.active
            self.active.discard(key)
        return existed

    def health(self):
        return {"adapter": self.kind, "available": True}

    def models(self):
        return [{"model": "fake-fast"}, {"model": "fake-deep"}]
