#!/usr/bin/env python3
"""Small deterministic Codex CLI double used by FastLab's integration tests."""

import json
import os
import re
import sys
import time
import uuid
from pathlib import Path


def argument_value(name):
    try:
        return sys.argv[sys.argv.index(name) + 1]
    except (ValueError, IndexError):
        return None


def emit(payload):
    print(json.dumps(payload, ensure_ascii=False), flush=True)


def trace(payload):
    destination = os.environ.get("FASTLAB_FAKE_TRACE")
    if not destination:
        return
    record = {"pid": os.getpid(), "time": time.time(), "cwd": str(Path.cwd()), **payload}
    with open(destination, "a", encoding="utf-8") as stream:
        stream.write(json.dumps(record, ensure_ascii=False) + "\n")


prompt = sys.stdin.read()
output_path = argument_value("-o")
schema_path = argument_value("--output-schema")
is_resume = "resume" in sys.argv
thread_id = "fake-" + uuid.uuid4().hex[:12]

emit({"type": "thread.started", "thread_id": thread_id})
if "-c" in sys.argv:
    emit({"type": "command.config", "message": " ".join(sys.argv[1:])})

if schema_path and Path(schema_path).name == "planner.schema.json":
    plan = {
        "title": "测试任务",
        "summary": "用三个子任务验证并行执行、依赖调度和任务分支汇总。",
        "subtasks": [
            {
                "key": "S1",
                "title": "创建第一份结果",
                "instructions": "创建 S1 的结果文件。",
                "weight": 2,
                "dependencies": [],
                "executor": "codex",
            },
            {
                "key": "S2",
                "title": "创建第二份结果",
                "instructions": "创建 S2 的结果文件。",
                "weight": 1,
                "dependencies": [],
                "executor": "codex",
            },
            {
                "key": "S3",
                "title": "完成依赖任务",
                "instructions": "在 S1、S2 完成后创建最终结果。",
                "weight": 1,
                "dependencies": ["S1", "S2"],
                "executor": "codex",
            },
        ],
        "acceptance": [
            {"id": "A1", "criterion": "三个结果文件存在。"},
            {"id": "A2", "criterion": "主分支没有被修改。"},
        ],
    }
    final = json.dumps(plan, ensure_ascii=False)
elif schema_path and Path(schema_path).name == "verifier.schema.json":
    final = json.dumps(
        {
            "passed": True,
            "summary": "测试验收通过。",
            "results": [
                {"id": "A1", "status": "passed", "evidence": "结果文件存在。"},
                {"id": "A2", "status": "passed", "evidence": "主分支提交未变化。"},
            ],
        },
        ensure_ascii=False,
    )
else:
    match = re.search(r"子任务 ID：?(S\d+)", prompt)
    key = match.group(1) if match else "S1"
    trace({"event": "start", "key": key})
    delay = float(os.environ.get("FASTLAB_FAKE_DELAY", "0"))
    if delay:
        time.sleep(delay)
    if os.environ.get("FASTLAB_FAKE_FAIL_KEY") == key:
        emit({"type": "item.completed", "item": {"type": "agent_message", "text": "模拟失败"}})
        sys.exit(7)
    filename = "followup-%s.txt" % key if is_resume else "result-%s.txt" % key
    if "CONFLICT" in prompt:
        filename = "shared.txt"
    Path(filename).write_text("generated by %s\n" % key, encoding="utf-8")
    final = json.dumps({"ok": True, "subtask": key}, ensure_ascii=False)
    trace({"event": "end", "key": key})

emit({"type": "item.completed", "item": {"type": "agent_message", "text": final}})
emit({"type": "turn.completed"})
if output_path:
    Path(output_path).write_text(final, encoding="utf-8")
